version: '3.4'

services:
  postgres:
    image: postgres:12.5
     environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1Qaz@wsx
    ports:
      - "5432:5432"
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
  testunadesk:
    image: ${DOCKER_REGISTRY-}testunadesk
    build:
      context: .
      dockerfile: TestUnaDesk/Dockerfile
  
